[package]
name = "freedesktop-entry"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]

[dependencies]
failure = { version = "0.1.1", features = ["derive"] }
lazy_static = "1.0"
mime = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
url = "1.7.0"
url_serde = "0.2.0"
